### ISSUE TITLE
Using czt in the freq2time function

### ISSUE THREAD

**Issue by e-d-n-a** [garrettj403/CZT#14]
I partially read the source article [1] and noticed this statement:

`In some cases[15], a modified version of the forward CZT algorithm, in which the logarithmic spiral contour was traversed in the opposite direction, was described as the ICZT algorithm. However, this method does not really invert the CZT. It works only in some special cases, e.g., when A=1 and W=e^(−2πi/n). That is, in the cases when the CZT reduces to the DFT. In the general case, i.e., when A,W∈C∖{0}, that method generates a transform that does not invert the CZT.`

So is it legitimate to use this approach in ["freq2time" utilizing the CZT](https://github.com/garrettj403/CZT/blob/c521771151e38e15605b81c6f56f49479f2cb8a4/czt.py#L296), instead of the also available ICZT?
I don't know what is meant with "special cases", so if it covers all ZoomFFT cases (with constant magnitudes).
Is it only necessary for A and W to lie on the unit circle here!?

[1] https://www.nature.com/articles/s41598-019-50234-9

**Comment by garrettj403** [comment]
Yes, `time2freq` and `freq2time` are essentially a DFT and IDFT, respectively, with |A|=|W|=1. The advantage of using the CZT package is that it is much faster because it is based on the FFT algorithm.
