### ISSUE TITLE
Problems running czt after install: No module named czt

### ISSUE THREAD

**Issue by maso27** [garrettj403/CZT#2]
When I attempt to run the example "zoom-dft.ipynb" (copy-pasted into a .py file), I receive this error:

```
Traceback (most recent call last):
  File "zoom-dft.py" line 6, in <module>
    import czt
ModuleNotFoundError: No module named 'czt'
```

I'm testing on Ubuntu 20.04 LTS
Installed czt with <**pip3 install czt**>
Ran the program with <**python3 zoom-dft.py**>

I have also tried downloading the zip from this github page and installing with <**python3 setup.py install --user**>
I receive the same error there.

I can make it work by copying czt.py into the same directory as the example, but I don't think the installer is working right.

**Comment by garrettj403** [comment]
I think this is because I was using ``packages=find_packages()`` in ``setup.py`` when ``czt`` isn't actually a package (i.e., not a directory with an ``__init__.py`` file). I've changed this line to ``py_modules=['czt']`` so it should work now. I've also updated the version on PyPI.

Let me know if that works for you.

**Comment by maso27** [comment]
I'm testing this on a fresh live boot of Ubuntu, so packages are pretty fresh from the start.

So when I type <**pip3 install czt**>, I get:
`ModuleNotFoundError: No module named 'numpy'`

After installing numpy, when I type <**pip3 install czt**>, I get:
`ModuleNotFoundError: No module named 'scipy'`

However, after installing scipy, everything works!

I think it's now a dependency issue, but a step in the right direction.

Thanks for the quick action!

**Comment by garrettj403** [comment]
I have Scipy and Numpy listed under ``install_requires`` in ``setup.py``, so I'm not sure why you're getting ``ModuleNotFoundError``. I've added a ``requirements.txt`` file, which might help.

Thanks for your feedback!
