### ISSUE TITLE
Argument ordering of toeplitz in t_method="mm"

### ISSUE THREAD

**Issue by LarsHuebner-LHNW** [garrettj403/CZT#3]
[scipy.linalg.toeplitz](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.toeplitz.html) requires arguments to be ordered (c,r) and not (r,c) in line 70. 
The error is hidden if M ==N (default for M = None), but for M != N matmul has wrong matrix shape.

**Comment by garrettj403** [comment]
Thank you for finding this error.

Fixed in f8d20fc.
