### ISSUE TITLE
ValueError for Integer arguments of A or W

### ISSUE THREAD

**Issue by LarsHuebner-LHNW** [garrettj403/CZT#4]
If a user uses e.g. A=1 then line 61 raises an Error, due to numpy's handling of integer values to negative powers ( like int**(-np.ndarray(dtype=int)) ).
Would suggest to add A=complex(A) and W=complex(W), and/or add dtype=float to np.aranges in lines 60 and 63

**Comment by garrettj403** [comment]
@LarsHuebner-LHNW , thank you for this suggestion.

I changed ``complex()`` to ``np.complex128()`` for higher precision in commit 9422dad.
