### ISSUE TITLE
Support for scipy.linalg.matmul_toeplitz as t_method

### ISSUE THREAD

**Issue by LarsHuebner-LHNW** [garrettj403/CZT#7]
scipy 1.6.0 now has its own implementation of [matmul_toeplitz](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.matmul_toeplitz.html). From its [source](https://github.com/scipy/scipy/blob/master/scipy/linalg/basic.py) I assume that it is the same as t_method="ce" with some checks added.

**Comment by garrettj403** [comment]
@LarsHuebner-LHNW, thank you for finding this new function.

I've added it as an option in commit e033d4a (via your pull request).

I've also added it to ``test_czt.py`` in f73a7ee.

I'll need to create some benchmarks to figure out which method is the fastest.
